### ISSUE TITLE
'CURL_4 not found' prevents compilation of Wflow and NCDatasets with existing Juliaup installation

### ISSUE THREAD

**Issue by pauwiersma** [eWaterCycle/ewatercycle-wflowjl#6]
Thanks for this package and the clear documentation. I have pywflow working now but I thought I might share a little problem I did encounter on the way. Unfortunately I'm not able to reproduce the error though, so I'll just describe the main points. 

I already had the most recent version of Julia (1.8.5) installed through Juliaup, and this was picked up by Juliacall so no new package was installed. But then during compilation both Wflow and NCDatasets failed to compile with the following error:
`curl: /usr/lib/x86_64-linux-gnu/libcurl.so: version 'CURL_4' not found ` which was required by NCDatasets. In `/usr/lib/x86_64-linux-gnu/libcurl.so` there were only `CURL_OPENSSL_4` symbols. The file it should've looked for was located at `home/.julia/juliaup/julia-1.8.5+0.x64.linux.gnu/lib/julia/libcurl.so`. After exporting this file to the LD_LIBRARY_PATH both NCDatasets and Wflow could be compiled and pywlow worked. However this is probably not a durable solution cause with every new version of Julia I will have to change this path. Our faculty computer scientist who helped me solve this problem did not have Julia installed on his system and he could install pywflow from the instructions without any difficulties.

As I wasn't able to reproduce the problem I'm not sure if this was specific to my system but perhaps it might still be useful to know. 

Finally an unrelated question: is the Julia Wflow version planned to be integrated in eWaterCycle soon? I already have the Python version running but I would like to switch in the near future.

**Comment by Peter9192** [comment]
Thanks for reporting Pau! I don't think we'll have time to look into this issue soon, but it's good to have it here in case more people run into the same problem.

> Finally an unrelated question: is the Julia Wflow version planned to be integrated in eWaterCycle soon? I already have the Python version running but I would like to switch in the near future.

I hope so. Keep an eye on https://github.com/eWaterCycle/ewatercycle/issues/336, if we go through with that idea it might make it simpler to add models alongside an existing ewatercycle installation.

**Comment by pauwiersma** [comment]
Thanks Peter! I'll keep an eye out

**Comment by BSchilperoort** [comment]
This issue is less relevant now we moved to the plugin structure. If the error reoccurs, try installing this plugin in a mamba environment in which you also install Julia.

If we manage to have Julia talk to GRPC (whether via Python or C) the model can be packaged in a container which would solve this problem entirely.
